services:
  navapi:
    image: registry.cn-hangzhou.aliyuncs.com/navfirst/navapi:1.0.0
    container_name: navapi
    hostname: navapi
    ports:
      - "8888:8888"
    environment:
      NAV_DB_TYPE: "${NAV_DB_TYPE:-pgsql}"
      NAV_PGSQL_HOST: "${NAV_PGSQL_HOST:-127.0.0.1}"
      NAV_PGSQL_PORT: "${NAV_PGSQL_PORT:-5432}"
      NAV_PGSQL_DB_NAME: "${NAV_PGSQL_DB_NAME:-nav_api}"
      NAV_PGSQL_USERNAME: "${NAV_PGSQL_USERNAME:-root}"
      NAV_PGSQL_PASSWORD: "${NAV_PGSQL_PASSWORD:-1qaz@WSX3edc}"
      NAV_PGSQL_MAX_IDLE_CONNS: "${NAV_PGSQL_MAX_IDLE_CONNS:-10}"
      NAV_PGSQL_MAX_OPEN_CONNS: "${NAV_PGSQL_MAX_OPEN_CONNS:-50}"
    volumes:
      - ./navapi/logback:/app/navapi/logback
      - ./navapi/data:/app/navapi/data
    restart: always
    networks:
      - nav-net

networks:
  nav-net:
    driver: bridge
